; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
board_upload.flash_size = 16MB
board_build.arduino.memory_type = qio_opi
board_build.psram_type = opi
build_flags = 
    -DBOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue
monitor_speed = 115200
monitor_filters = esp32_exception_decoder, send_on_enter

[env:test_motor]
build_src_filter = +<test_motor.cpp> +<Motor.cpp> -<main.cpp> -<test_encoder.cpp> -<Encoder.cpp> -<Gyro.cpp>
lib_deps = 
	madhephaestus/ESP32Servo@^3.0.5
    as5600

[env:test_encoder]
build_src_filter = +<test_encoder.cpp> +<Encoder.cpp> -<main.cpp> -<test_motor.cpp> -<Motor.cpp> -<Gyro.cpp>
lib_deps = 
    as5600

[env:test_infrared]
build_src_filter = +<test_infrared.cpp> +<InfraredSensor.cpp> -<main.cpp> -<test_motor.cpp> -<test_encoder.cpp> -<Encoder.cpp> -<Motor.cpp> -<Gyro.cpp>

[env:test_mpu6500]
build_src_filter = -<*> +<test_mpu6500.cpp> +<MPU6500.cpp>
lib_deps =
    https://github.com/hideakitai/MPU9250.git

[env:i2c_scanner]
build_src_filter = -<*> +<i2c_scanner.cpp>
lib_deps =
    https://github.com/hideakitai/MPU9250.git

[env:main]
build_src_filter = +<main.cpp> +<Motor.cpp> +<Encoder.cpp> +<Gyro.cpp> -<test_*>
lib_deps = 
	madhephaestus/ESP32Servo@^3.0.5
    as5600    

    